### PR TITLE
Tiny QOL change for ProfileCommand

### PR DESCRIPTION
**Pull request by Victor4X**
Local PP now also displays the difference to Live PP.  
This makes it easier to see improvements at a glance, and was a QOL change I made when I was helping in the reddit PP Calculation Thread: https://www.reddit.com/r/osugame/comments/al27eu/pp_calculation_thread/   

Example:
image

### CODE REVIEW

**Comment by peppy** [comment]
Can you change the formatting to
`Local PP: 5562,0 (+219,5)`?

I think the format should be `$"{totalDiffPP:+F1;-F1;-}"` (please check this is correct).

**Comment by tybug** [comment]
Should rather be `{totalDiffPP:+#.#;-#.#;-0}` for single decimal precision and a `-0` for 0 difference

**Comment by peppy** [comment]
It should be a `-` with no difference, or `+0`, but not `-0`.

**Comment by tybug** [comment]
Ah okay, I thought `Local PP: 5562,6 (- Difference)` might look a bit strange with no number next to the sign

**Comment by Victor4X** [comment]
Hey! I've removed the word "Difference" and updated the number formatting to include the sign.
With this implementation it rounds to a single decimal, and looks like this:

If positive:
if positive

If negative:
if negative

If zero:
if zero

And here is how it would look with double decimal precision:
if positive 2 digits

**Pull request merged**
