### PR TITLE
Simulate osu!mania scores by accuracy and counts

### PR DESCRIPTION
**Pull request by kionell**
Since osu!mania now uses accuracy -> pp system instead of score -> pp, mania score simulation needs to be updated in both osu-tools and osu-tools GUI. However, i heard that you want to revert this change so idk if this pull request is still relevant or not.

### CODE REVIEW

**Comment by kionell** [comment]
Also, is there any reason why in [ScoreInfoExtensions](https://github.com/ppy/osu/blob/master/osu.Game/Scoring/Legacy/ScoreInfoExtensions.cs#L92) all 100's are Ok's, while everywhere else they are Good's?

**Comment by smoogipoo** [comment]
> while everywhere else

Where do you mean?

**Comment by S1n1st3rn3ss** [comment]
[OsuSimulateCommand](https://github.com/ppy/osu-tools/blob/master/PerformanceCalculator/Simulate/OsuSimulateCommand.cs#L47) as one of the cases

**Comment by kionell** [comment]
> Where do you mean?

Oh, at first i thought that this is the case for osu!taiko simulate command and how osu-web displays osu!taiko leaderboard counts, but then I read [this](https://github.com/ppy/osu/blob/master/osu.Game/Scoring/Legacy/ScoreInfoExtensions.cs#L69) and my questions are gone. 
The only confusing part that I found is in [osu!standard simulate command](https://github.com/ppy/osu-tools/blob/master/PerformanceCalculator/Simulate/OsuSimulateCommand.cs#L83). I mean this command uses greats (for 300's) and goods (for 100's) which is wrong (if i'm not missing anything), because from [ScoreInfoExtensions](https://github.com/ppy/osu/blob/master/osu.Game/Scoring/Legacy/ScoreInfoExtensions.cs#L92) we know that there are should be Ok's.

**Comment by smoogipoo** [comment]
At one point in time, osu! used to use Great/Good/Meh. These days every non-mania ruleset uses Great/Good/Ok. So the osu! simulate command (and potentially others) is out of date.

**Comment by minisbett** [comment]
I believe this is outdated and implemented by now, so it can be closed.

**Pull request closed without merging**
