### PR TITLE
Account for CL mod when generating HitResults

### PR DESCRIPTION
**Pull request by Givikap120**
Depends on #231 

Adds mods parameter `GenerateHitResults` so you can generate correct hitresults for CL scores.

### CODE REVIEW

**Comment by minisbett** [comment]
This PR seems to make things more complicated at no gain. The accuracy calculation already works fine with CL and non-CL, even when exclusively generating non-CL hit statistics and using the Lazer accuracy formula.

**Comment by Givikap120** [comment]
> This PR seems to make things more complicated at no gain. The accuracy calculation already works fine with CL and non-CL, even when exclusively generating non-CL hit statistics and using the Lazer accuracy formula.

It's literally incorrect for CL scores

**Comment by minisbett** [comment]
Oh I think you're right. Can you maybe close this PR and include these changes in #231 instead? It's annoying to review it this way

**Comment by Givikap120** [comment]
> Oh I think you're right. Can you maybe close #231? I think it makes more sense to have all of this in a single PR, easier to review

I split it exactly for reason of being easier to review.
Because adding `mods` param to the function without refactor makes confusing way of calculating hitresults even more confusing.

**Comment by minisbett** [comment]
> > Oh I think you're right. Can you maybe close #231? I think it makes more sense to have all of this in a single PR, easier to review
> 
> I split it exactly for reason of being easier to review. Because adding `mods` param to the function without refactor makes confusing way of calculating hitresults even more confusing.

ok yeah fair, after looking at the code for longer maybe

**Review by smoogipoo — APPROVED** [review]

**Comment by smoogipoo** [comment]
Ah, I didn't notice the dependency here...

**Comment by minisbett** [comment]
Wasn't it discussed in #difficulty-osu that the complicated accuracy calculation here can be simplified here? https://discord.com/channels/188630481301012481/380598781432823815/1307180578906312724

**Comment by minisbett** [comment]
So maybe revert this PR until #231 is merged and a more proper accuracy calculation implemented?

**Pull request merged**
