### PR TITLE
Add flashlight attribute and update packages

### PR DESCRIPTION
**Pull request by smoogipoo**

### CODE REVIEW

**Comment by MBmasher** [comment]
Does `FlashlightRating` have a zero value when Flashlight mod isn't enabled?

**Comment by smoogipoo** [comment]
No, is that an issue worth fixing?

**Comment by MBmasher** [comment]
I'm actually not sure. I feel like it makes sense for it to be zero when it's not enabled, although it's a weird case.

**Comment by peppy** [comment]
I would honestly hope we aren't storing it anywhere when flashlight is off? Seems like a huge waste of resources otherwise.

**Comment by smoogipoo** [comment]
Originally it wasn't 0 in the difficulty calculator because it wasn't included into SR and so it could be pulled from the base mod combinations (combinations excluding FL).

But now that diffcalc runs over +FL combinations as well, this should be changed osu!-side.

**Comment by smoogipoo** [comment]
This PR can go in as is in any case.

**Comment by peppy** [comment]
So we do want to show "flashlight rating" as zero on all outputs from this tool?

**Comment by smoogipoo** [comment]
I've changed it to not output.

**Review by peppy — APPROVED** [review]

**Pull request merged**
