### PR TITLE
Reworked hit result generator based on accuracy

### PR DESCRIPTION
**Pull request by Givikap120**
It used to just spam 50s until it reach target accuracy
Now it's actually trying to fit it in realistic way

### CODE REVIEW

**Review by tsunyoku — CHANGES_REQUESTED** [review]
Would be nice to add explanation on what this is doing and why. All I see is logic with no clear reasoning on why it does what it does.

**Comment by Givikap120** [comment]
> Would be nice to add explanation on what this is doing and why. All I see is logic with no clear reasoning on why it does what it does.

Added very detailed explanation of what I'm doing here. You can remove unnecessary things.

**Review by stanriders — CHANGES_REQUESTED** [review]
Please copy your implementation to the CLI perfcalc as well: https://github.com/ppy/osu-tools/blob/master/PerformanceCalculator/Simulate/OsuSimulateCommand.cs#L63

**Comment by Givikap120** [comment]
> Please copy your implementation to the CLI perfcalc as well: https://github.com/ppy/osu-tools/blob/master/PerformanceCalculator/Simulate/OsuSimulateCommand.cs#L63

Fixed

**Review by stanriders — CHANGES_REQUESTED** [review]
Please fix CI issues

**Comment by stanriders** [comment]
image

**Comment by smoogipoo** [comment]
CodeFactor is fine, don't mind that too much.

**Review by stanriders — APPROVED** [review]
I'd say a lot of this is redundant (does it really matter if scores below 25% accuracy are accurately calculated?..) but I guess it doesnt hurt to have

**Pull request merged**
